%YAML:1.0

#common parameters

imu_topic: "/imu"
image_topic: "/rgb/image_raw"
depth_topic: "/depth_to_rgb/image_raw"
need_compress: 1 # 0 for subscriping compressed image  

result_path: "/home/javens/Workspace/catkin_dio/result/"
name: kinect_dk



camera_name: camera
image_width: 640
image_height: 480


#distortion_parameters:
k1: 0
k2: 0
p1: 0
p2: 0

#projection_parameters:
fx: 320.
fy: 320.
cx: 319.5
cy: 239.5


extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.0048388, -0.999987, 0.00149534,
          0.029966, 0.00163969, 0.99955,
          -0.999539, -0.0047919, 0.0299736]    
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.0286967, -0.001157699, -0.0471852]


#Volume parameters

voxel_size: 20
truncated_size: 60
voxel_x: 800
voxel_y: 500
voxel_z: 1000 

init_x: -1000
init_y: 0
init_z: 1000

#Controller parameters
render_surface: 1
PST_path: "/home/javens/Workspace/catkin_dio/src/PST/"
save_trajectory: 1
save_scene: 1

max_iteration: 18
scaling_coefficient1: 0.25
scaling_coefficient2: 0.15
init_fitness: 0.6
momentum: 0.9
scaling_inherit_directly: 0



